### ISSUE TITLE
Create a UT plan with proper test cases and acceptance crietria

### ISSUE THREAD

**Issue by Bhagavad-Geetha-ML** [maplelabs/apm-jenkins-plugin#6]

**Comment by anushkabishnoi** [comment]
Hello, this is my first experience with open source contributions. Would really appreciate it if you explained exactly what is needed to be done.

I would love to work on this issue.

Thanks in advance! :)

**Comment by Bhagavad-Geetha-ML** [comment]
Hi Anushka,

Thanks for your interest to take it up.
Can you please join discord, so that we can communicate through that?
https://discord.gg/PhRYYJW3


Thanks,
Geetha
