### ISSUE TITLE
Get the code acceptance/review procedure from Jenkins team

### ISSUE THREAD

**Issue by Bhagavad-Geetha-ML** [maplelabs/apm-jenkins-plugin#7]
Details are there in below URL:
https://wiki.jenkins.io/display/JENKINS/Hosting+Plugins
https://www.velotio.com/engineering-blog/jenkins-plugin-development

**Comment by Jithendiran-EK-ML** [comment]
Have a jenkins-ci.org account
Document plugin on this wiki and track issue in JIRA
Add developer info in POM file
